
name: Semantic Release


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu_latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
        node-version: 14.17

      - name: Install Dependecies
        run: npm install

      - name: Build App
        run: npm build

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      


